services:
  # 1. Unified Fullstack Web Service
  - type: web
    name: redexcom-fullstack
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: ENV_MODE
        value: prod
      - key: NODE_ENV
        value: production
